#
# Copyright 2024 Delphix. All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# InfluxDB 2.x Configuration
#

bolt-path = "/var/lib/influxdb2/influxdb.bolt"
engine-path = "/var/lib/influxdb2/engine"
http-bind-address = "127.0.0.1:8086"
log-level = "warn"
