name: Python Lint

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        flake8 . --show-source --statistics
